[project]
name = "doom-bot"
version = "79.0"
requires-python = "==3.13.*"
dependencies = [
    "aiohttp",
    "anyio>=4.12.0",
    "attu-models",
    "httpx",
    "hypercorn>=0.16.0",
    "mwparserfromhell",
    "py-cord[speed]<3",
    "pydantic",
    "pymongo>=4.6.0",
    "quart-rate-limiter>=0.9.0",
    "quart>=0.19.0",
    "structlog>=24.0.0",
    "tomlkit",
    "webauthn>=2.0.0",
]

[tool.uv]
package = false

[tool.uv.sources]
attu-models = { workspace = true }
