services:
  core:
    build: .
    restart: always
    command: python -u /app/attu-bot.py
    environment:
      ATTU_CONFIG_FILE: /app/attu-bot.toml
    volumes:
    - ./attu-bot.toml:/app/attu-bot.toml
    logging:
      driver: journald

