[tool.ruff]
select = [
  "E4",
  "E7",
  "E9",
  "F",
  "Q",
  "W",
  "I",
  "UP",
  "ASYNC",
  "S",
  "A",
  "CPY",
  "COM",
  "SIM",
]
# select = ["ALL"]

ignore = [
  "E501", # line-length violations
]

exclude = [".venv", "debug.py", "calendar.py"]
target-version = "py312"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
# Use a single line after each import block.
lines-after-imports = 1

[tool.ruff.lint.pydocstyle]
convention = "google"
