[project]
name = "attu-server"
version = "0.0.0"
requires-python = "==3.13.*"
dependencies = [
    "attu-logging",
    "attu-models",
    "fastapi>=0.115.0",
    "httpx",
    "pydantic",
    "tomlkit",
    "uvicorn>=0.34.0",
]

[tool.uv]
package = false

[tool.uv.sources]
attu-logging = { workspace = true }
attu-models = { workspace = true }
