config_version = "1.8.0-pre6"

[auth.bot]
token = "TOKEN_GOES_HERE"

[auth.wiki]
key = "KEY_GOES_HERE"
page = "Example:Home"
user = "WikiBot@WikiBot"
endpoint = "https://example.org"

[discord.guilds]
primary = 1000000000000000000
authorized = [1000000000000000000, 2000000000000000000]

[imports]
