[project]
name = "casino-bot"
version = "0.1.0"
requires-python = "==3.13.*"
dependencies = [
    "attu-logging",
    "nova-core",
    "attu-models",
    "py-cord[speed]<3",
    "pymongo>=4.6.0",
    "pydantic",
    "tomlkit",
]

[tool.uv]
package = false

[tool.uv.sources]
attu-logging = { workspace = true }
nova-core = { workspace = true }
attu-models = { workspace = true }
