# SPDX-License-Identifier: Apache-2.0
"""attu_models | shared mongodb document models and repositories."""

from .connection import MongoStorage
from .documents import (
    ChatChannelConfig,
    ChatCharacterDocument,
    ChatConfigDocument,
    ChatSourceDocument,
    EggDocument,
    EggUserDocument,
    FamilyDocument,
    GuildConfigDocument,
    MessageDocument,
    ReloadSignalDocument,
    ReminderDocument,
    StarredMessageDocument,
    SystemConfigDocument,
    ThemeDocument,
    WikiViewDocument,
    YearDocument,
    YearMarkerDocument,
)
from .repositories import (
    ChatCharacterRepository,
    ChatConfigRepository,
    ChatSourceRepository,
    ConfigRepository,
    EggRepository,
    EggUserRepository,
    FamilyRepository,
    MessageRepository,
    ReloadSignalRepository,
    ReminderRepository,
    StarboardRepository,
    WikiViewRepository,
    YearMarkerRepository,
    YearRepository,
)


__all__ = [
    'ChatChannelConfig',
    'ChatCharacterDocument',
    'ChatCharacterRepository',
    'ChatConfigDocument',
    'ChatConfigRepository',
    'ChatSourceDocument',
    'ChatSourceRepository',
    'ConfigRepository',
    'EggDocument',
    'EggRepository',
    'EggUserDocument',
    'EggUserRepository',
    'FamilyDocument',
    'FamilyRepository',
    'GuildConfigDocument',
    'MessageDocument',
    'MessageRepository',
    'MongoStorage',
    'ReloadSignalDocument',
    'ReloadSignalRepository',
    'ReminderDocument',
    'ReminderRepository',
    'StarboardRepository',
    'StarredMessageDocument',
    'SystemConfigDocument',
    'ThemeDocument',
    'WikiViewDocument',
    'WikiViewRepository',
    'YearDocument',
    'YearMarkerDocument',
    'YearMarkerRepository',
    'YearRepository',
]
