# SPDX-License-Identifier: Apache-2.0
"""attu_models | shared mongodb document models and repositories."""

from .connection import MongoStorage
from .documents import (
    BoardEntryDocument,
    EggDocument,
    EggUserDocument,
    FamilyDocument,
    GuildConfigDocument,
    MessageAuthor,
    MessageContent,
    MessageDocument,
    MessageRefs,
    ReactionDocument,
    ReloadSignalDocument,
    ReminderDocument,
    StarredMessageDocument,
    SystemConfigDocument,
    ThemeDocument,
    WikiViewDocument,
    YearDocument,
    YearMarkerDocument,
)
from .repositories import (
    ConfigRepository,
    EggRepository,
    EggUserRepository,
    EntryRepository,
    FamilyRepository,
    MessageRepository,
    ReactionRepository,
    ReloadSignalRepository,
    ReminderRepository,
    StarboardRepository,
    WikiViewRepository,
    YearMarkerRepository,
    YearRepository,
)


__all__ = [
    'BoardEntryDocument',
    'ConfigRepository',
    'EggDocument',
    'EggRepository',
    'EggUserDocument',
    'EggUserRepository',
    'EntryRepository',
    'FamilyDocument',
    'FamilyRepository',
    'GuildConfigDocument',
    'MessageAuthor',
    'MessageContent',
    'MessageDocument',
    'MessageRefs',
    'MessageRepository',
    'MongoStorage',
    'ReactionDocument',
    'ReactionRepository',
    'ReloadSignalDocument',
    'ReloadSignalRepository',
    'ReminderDocument',
    'ReminderRepository',
    'StarboardRepository',
    'StarredMessageDocument',
    'SystemConfigDocument',
    'ThemeDocument',
    'WikiViewDocument',
    'WikiViewRepository',
    'YearDocument',
    'YearMarkerDocument',
    'YearMarkerRepository',
    'YearRepository',
]
